version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://campus_user:campus_pass@postgres:5432/campus_sports_db
      - SECRET_KEY=campus_sports_hub_hackathon_super_secret_jwt_key_2026
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=campus_user
      - POSTGRES_PASSWORD=campus_pass
      - POSTGRES_DB=campus_sports_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
